site_name: OE Logic Guide
site_url: https://space-cee.github.io/oe-logic-guide/
theme:
  name: material
  palette:
    - scheme: slate       # Dark mode by default
      primary: indigo     # You can pick another main color (e.g. teal, amber, deep purple)
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default     # Optional light mode
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.expand      # collapsible categories in sidebar
    - navigation.instant     # sidebar highlights current page
    - search.highlight
    - search.suggest
    - toc.integrate          # integrate table of contents into sidebar

nav:
  - Home: index.md
  - Block Data (TEST): json-viewer.md
  - OE Logic:
        - Communication: OE LOGIC/COMMUNICATION/Placeholder.md
        - Converter:
          - Byte: OE LOGIC/CONVERTER/Byte.md
          - Color: OE LOGIC/CONVERTER/Color.md
          - Units: OE LOGIC/CONVERTER/Units.md
          - Vector: OE LOGIC/CONVERTER/Vector.md
        - Display:
          - Lamps: OE LOGIC/DISPLAY/Placeholder.md
        - Gates:
          - GATE: "OE LOGIC/GATE/Gate.md"
          # Add more Gates blocks here
        - GUI: OE LOGIC/GUI/Placeholder.md
        - Math: 
          - MATH: "OE LOGIC/MATH/Math.md"
          # Add more Math blocks here
          - Byte: OE LOGIC/MATH/Byte.md
          - Trigonometry: OE LOGIC/MATH/Trigonometry.md
        - Memory: OE LOGIC/MEMORY/Placeholder.md
        - Other: OE LOGIC/OTHER/Placeholder.md
        - Particle: OE LOGIC/PARTICLE/Placeholder.md
        - Sensor: OE LOGIC/SENSOR/Placeholder.md
        - Sound: OE LOGIC/SOUND/Placeholder.md
        - String: OE LOGIC/STRING/Placeholder.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/space-cee/oe-logic-guide
